config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  root to: "pages#home"

  resources :users, only: [:show, :index] do
    resources :characters, only: [:new, :create, :show, :index, :update] do
      member do
        post 'travel', to: 'characters#travel'
      end
      resources :battles, only: [:new, :create, :show] do
        member do
          post 'fight', to: 'battles#fight'
          post 'attack_enemy', to: 'battles#attack_enemy'
        end
      end
    end
  end

  resources :locations, only: [:new, :create, :destroy] do
    resources :enemies, only: [:new, :create]
  end
  # resources :locations, only: [:new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
      <%= image_tag "temporary_logo.png", class: "navbar-logo" %>
      <h1 class="navbar-title ms-2"><b>Battle Adventure Game</b></h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link text-orange" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Characters", user_characters_path(current_user), class: "nav-link text-orange" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if true == false %>
                <%= cl_image_tag(current_user.photo.key, class: "avatar", alt: "User Avatar") %>
              <% else %>
                <%= image_tag("default_avatar.png", class: "avatar", alt: "Default Avatar") %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", root_path, class: "dropdown-item" %>
              <%= link_to "Edit My Profile", root_path, class: "dropdown-item" %>
              <%= link_to "Chat", root_path, class: "dropdown-item" %>
              <%= link_to "User Directory", root_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn btn-outline-orange" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>