config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  root to: "pages#home"

  resources :users, only: [:show, :index] do
    resources :characters, only: [:new, :create, :show, :index, :update] do
      member do
        post 'travel', to: 'characters#travel'
      end
      resources :battles, only: [:new, :create, :show] do
        member do
          post 'fight', to: 'battles#fight'
          post 'attack_enemy', to: 'battles#attack_enemy'
        end
      end
    end
  end

  resources :locations, only: [:new, :create, :destroy] do
    resources :enemies, only: [:new, :create]
  end
  # resources :locations, only: [:new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  has_one :location, dependent: :destroy
end

app/controllers/character_controller.rb
class CharacterController < ApplicationController

  def show
    @character = set_character
  end

  def index
    @characters = current_user.Character.all
  end

  def new
    @user = current_user
    @character = Character.new
  end

  def create
    @character = Character.new(user: current_user, name: @character, health: 100, hunger: 100, attack:, 1, location: "starting")
    if @note.save
      redirect_to user_character_notes_path(current_user, @character), notice: 'Character was successfully created.'
    else
      render :new
    end
  end

  private

  def set_character
    @character = Character.find(params[:character_id])
  end

  def character_params
    params.require(:character).permit(:user_id, :name, :health, :hunger, :attack, :location)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def show
    @character = set_character
    @location = @character.location
    @enemies = Enemy.where(location: @location.id)
    @battles_exist = Battle.where(character_id: @character.id)
    @user = current_user
  end

  def index
    @characters = Character.all
    @user = current_user
  end

  def new
    @user = current_user
    @character = Character.new
  end

  def create
    starting_location = starting_location_generation
    @character = Character.new(user_id: current_user.id, name: params[:character][:name], health: 100, hunger: 100, attack: 1, location: starting_location)
    if @character.save
      Enemy.create_chicken(starting_location)
      redirect_to user_characters_path(current_user)
    else
      render :new
    end
  end

  def travel
    @character = set_character
    @character.location.destroy
    @character.location = randomize_location(@character)
    redirect_to user_character_path(params[:user_id], params[:id])
  end

  def randomize_location(character)
    possible_locations = ["meadow", "woods"]
    sampled_location = possible_locations.sample

    case sampled_location
    when "meadow"
      Location.create_meadow(character)
    when "woods"
      Location.create_woods(character)
    else
      no_location_checker(character)
    end
  end

  def starting_location_generation
    Location.create(character_id: params[:character][:id], name: "starting", description: "You wake up naked and afraid in a new land, with nothing to defend yourself but your fists")
  end

  def no_location_checker(character)
    starting_location = starting_location_generation if character.location.nil?
    character.location = starting_location
  end

  private

  def set_character
    @character = Character.find(params[:id])
  end

  def character_params
    params.require(:character).permit(:user_id, :name, :health, :hunger, :attack, :location)
  end
end

app/views/characters/index.html.erb
<%= link_to 'New Character', new_user_character_path(@user), class: "" %>
<% if @characters %>
  <% @characters.each do |character| %>
    <div class="character-card">
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
      <div class="character-card-info">
        <h2><%= character.name %></h2>
        <p>health:<%= character.health %></p>
        <p>hunger:<%= character.hunger %></p>
        <p>attack:<%= character.attack %></p>
        <% if character.location %>
        <p>location:<%= character.location.name %></p>
        <% end %>
        <div>
          <%= link_to 'Play', user_character_path(@user, character.id), class: "" %>
        </div>
      </div>
      <div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/characters/new.html.erb
<%= simple_form_for([current_user, @character]) do |f| %>
  <%= f.input :name, label: 'Your characters name please', error: 'Name is mandatory, please specify one' %>
  <%= f.button :submit %>
<% end %>

app/views/characters/show.html.erb
<div class="character-show-body" style="background: url(<%= asset_path("location_backgrounds/#{@character.location.name}.png") %>) no-repeat;">
<div class="character-actions">

<% if @battles_exist %>
    <% @battles_exist.each do |battle| %>
    <p>  <%= link_to 'continue battle', user_character_battle_path(@user.id, @character.id, battle.id), class: "" %></p>
    <% end %>
  <% else %>
  <%= button_to 'Travel to a new location', travel_user_character_path(params[:user_id], params[:id]), method: :post, class: "" %>
  <%= button_to 'Look for trouble', fight_user_character_battle_path(params[:user_id], params[:id]), method: :post, class: "" %>
  <button>search for valuables</button>
  <button>camp for the night</button>
<% end %>

</div>
  <div class="character-show-info">
          <h3><%= @location.description %></h3>
          <h2><%= @character.name %></h2>
          <p>health:<%= @character.health %></p>
          <p>hunger:<%= @character.hunger %></p>
          <p>attack:<%= @character.attack %></p>
  </div>
    <div class="location-enemies">
    <p>enemies in the area:</p>
<% @enemies.each do |enemy| %>
  <p><%= enemy.name %></p>
<% end %>
  </div>
</div>
<% if flash[:notice] %>
  <p class="flash-notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
  <p class="flash-alert"><%= flash[:alert] %></p>
<% end %>