config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  root to: "pages#home"

  resources :users, only: [:show, :index] do
    resources :characters, only: [:new, :create, :show, :index, :update] do
      member do
        post 'travel', to: 'characters#travel'
      end
      resources :battles, only: [:new, :create, :show] do
        member do
          post 'fight', to: 'battles#fight'
          post 'attack_enemy', to: 'battles#attack_enemy'
        end
      end
    end
  end

  resources :locations, only: [:new, :create, :destroy] do
    resources :enemies, only: [:new, :create]
  end
  # resources :locations, only: [:new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/battle.rb
class Battle < ApplicationRecord
  belongs_to :character
  belongs_to :enemy
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  def new
    @user = current_user
    @character = set_character
    @location = set_location
  end

  def show
    @user = current_user
    @character = set_character
    @battle = Battle.find(params[:id])
    @enemy = @battle.enemy
  end

  def attack_enemy
    @user = current_user
    @character = set_character
    @battle = Battle.find(params[:id])
    @enemy = @battle.enemy
    if [true, true, true, true, false].sample == true
      new_enemy_health = @enemy.health - @character.attack
      @enemy.health = new_enemy_health
      @enemy.save
    end
    if [true, true, true, true, false].sample == true
      new_character_health = @character.health - @enemy.attack
      @character.health = new_character_health
      @character.save
    end
    redirect_to user_character_battle_path(@user.id, @character.id, @battle.id), notice: 'Battle was successfully created.'
  end

  def create
    @user = current_user
    @character = set_character
    @battle = Battle.new(battle_params.merge(character_id: @character.id))

    if @battle.save
      redirect_to user_battles_path(current_user), notice: 'Battle was successfully created.'
    else
      render :new
    end
  end

  def fight
    @user = current_user
    @character = set_character
    @location = set_location
    @enemy = @location.enemies.sample
    @battle = Battle.new(character_id: @character.id, enemy_id: @enemy.id)

    if @battle.save
      redirect_to user_character_battle_path(@user.id, @character.id, @battle.id), notice: 'Battle was successfully created.'
    else
      redirect_to user_character_path(@user.id, @character.id), alert: 'Failed to create battle.'
    end
  end

  private

  def set_character
    @character = Character.find(params[:character_id])
  end

  def set_location
    @character.location
  end

  def battle_params
    params.require(:battle).permit(:character_id, :enemy_id)
  end
end

app/views/battles/show.html.erb
<p><%= @character.name %> is going to fight <%= @enemy.name %></p>
      <div class="character-card-info">
        <h2> <%= @character.name %> </h2>
        <p>health: <%= @character.health %> </p>
        <p>hunger: <%= @character.hunger %> </p>
        <p>attack: <%= @character.attack %> </p>
        <% if @character.location %>
        <p>location: <%= @character.location.name %> </p>
        <% end %>
      </div>

            <div class="enemy-card-info">
        <h2><%= @enemy.name %> </h2>
        <p>health: <%= @enemy.health %> </p>
        <p>attack: <%= @enemy.attack %> </p>
      </div>

<p>what will you do?</p>
<%= button_to 'Attack', attack_enemy_user_character_battle_path(params[:user_id], params[:character_id]), method: :post, class: "" %>
<%= button_to 'block', fight_user_character_battle_path(params[:user_id], params[:id]), method: :post, class: "" %>
<%= button_to 'item', fight_user_character_battle_path(params[:user_id], params[:id]), method: :post, class: "" %>
<%= button_to 'run', fight_user_character_battle_path(params[:user_id], params[:id]), method: :post, class: "" %>

<%= @battle.id %>